### ISSUE TITLE
feature_momentum and CustomPade are missing in source code

### ISSUE THREAD

**Issue by yan9qu** [KingJamesSong/DifferentiableSVD#1]

**Comment by KingJamesSong** [comment]
Hi, 

  Thanks for your interest!
  
  1) CustomPade is actually SVDPade; it is just a different name. You can either change the code name to CustomPade or change the name of pre-trained weight to SVDPade
  
  2) feature_momentum is never used in the code. You can set strict=False when you load the pre-trained weights.
  
  Let me know if your problem is solved.

**Comment by yan9qu** [comment]
That works for me, thanks.
And could you please offer an tutorial for multi-gpu training? I met some DDP errors~

**Comment by KingJamesSong** [comment]
Hi,

  For distributed training, you could change the hyper-parameter world_size to the number of processes (GPUs) in https://github.com/KingJamesSong/DifferentiableSVD/blob/main/main.py#L59
  
  Then you could start the training script by 

> python -m torch.distributed.launch --use-env main.py

**Comment by yan9qu** [comment]
Thanks for immediate help, I will try this later.

Sent with Spark
2023年4月19日 +0800 15:23 YueSong ***@***.***>，写道：
